/* Optimized WebP assets use explicit responsive variants; no runtime image service. */
/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import {Header} from '@/components/home/header';
import {HomeInteractions} from '@/components/home/interactions';
import {Icon} from '@/components/home/icons';
import {ShowTrailer} from './show-trailer';
import {ShowInteractions} from './show-interactions';
import {getShow,showPath,type Show,type ShowDate,type ShowImage} from '@/content/shows';
import {socials} from '@/content/site';

function ImageAsset({image,hero=false}:{image:ShowImage;hero?:boolean}){return <img src={image.src} srcSet={image.srcSet} sizes="(max-width:767px) calc(100vw - 40px), (max-width:1099px) 38vw, 440px" width={image.width} height={image.height} alt={image.alt} fetchPriority={hero?'high':undefined} loading={hero?'eager':'lazy'} decoding="async"/>}
function TicketLink({href,event,label='Biglietti'}:{href:string;event:string;label?:string}){return <a className="button primary" href={href} target="_blank" rel="noopener noreferrer" data-event={event}><Icon name="ticket"/>{label}<Icon name="arrow"/></a>}
function mainTicket(show:Show,now:number){return show.dates.find(date=>date.ticketUrl&&date.status!=='cancelled'&&date.status!=='sold_out'&&date.status!=='postponed'&&Date.parse(date.startDate)>now)?.ticketUrl}
export function ShowHero({show,now}:{show:Show;now:number}){const tickets=mainTicket(show,now);return <section className="show-hero" aria-labelledby="show-title"><div className="show-hero-copy"><p className="show-eyebrow">{show.eyebrow}</p><h1 id="show-title">{show.title}</h1><p className="show-tagline">{show.tagline}</p><p className="show-description">{show.description}</p><div className="show-actions">{tickets&&<TicketLink href={tickets} event="show_ticket_click_hero"/>}{show.dates.length>0&&<a className="button secondary" href="#show-dates">Scopri le date<Icon name="down"/></a>}</div></div><figure className="show-poster"><a href={show.heroImage.src} target="_blank" rel="noopener noreferrer" aria-label={`Apri la locandina di ${show.title}`} data-event="show_gallery_open"><ImageAsset image={show.heroImage} hero/></a></figure></section>}
export function ShowIntro({show}:{show:Show}){return <section className="show-section show-intro" aria-labelledby="show-intro-title"><div><p className="show-eyebrow">Lo spettacolo</p><h2 id="show-intro-title">{show.tagline}</h2><p>{show.longDescription[0]}</p><Link className="show-text-link" href="/chi-sono/">Chi è Peppe Ventura <Icon name="arrow"/></Link></div><div>{show.introImage&&<ImageAsset image={show.introImage}/>} {show.longDescription.slice(1).map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div></section>}
const dateStatuses={available:'Biglietti disponibili',sold_out:'Sold out',cancelled:'Annullato',postponed:'Posticipato',coming_soon:'In arrivo'};
export function ShowDateRow({date,now}:{date:ShowDate;now:number}){
 const [year,month,day]=date.startDate.slice(0,10).split('-');
 const past=Date.parse(date.startDate)<now;
 const canBuy=date.ticketUrl&&!past&&!['sold_out','cancelled','postponed','coming_soon'].includes(date.status??'');
 return <li className="show-date-row"><time dateTime={date.startDate}><strong>{day}</strong><span>{['GEN','FEB','MAR','APR','MAG','GIU','LUG','AGO','SET','OTT','NOV','DIC'][Number(month)-1]}</span><span>{year}</span></time><div className="show-date-place"><h3>{date.city}</h3><p>{date.venue}</p><span>{date.address}</span></div><div className="show-date-time"><p>Ore {date.time}</p>{(past||date.status)&&<span>{past?'Data conclusa':dateStatuses[date.status!]}</span>}</div>{canBuy?<TicketLink href={date.ticketUrl!} event="show_ticket_click_date"/>:<span className="show-date-status">{past?'Data conclusa':date.status?dateStatuses[date.status]:'Biglietteria da confermare'}</span>}</li>
}
export function ShowDates({show,now}:{show:Show;now:number}){return show.dates.length>0?<section className="show-section show-dates" id="show-dates" aria-labelledby="show-dates-title"><div className="show-section-heading"><h2 id="show-dates-title">{show.dates.some(date=>Date.parse(date.startDate)>now)?'Prossime date':'Date dello spettacolo'}</h2><span>Biglietti online</span></div><ol>{[...show.dates].sort((a,b)=>Date.parse(a.startDate)-Date.parse(b.startDate)).map(date=><ShowDateRow key={date.id} date={date} now={now}/>)}</ol></section>:null}
export function ShowGallery({images,title='In scena'}:{images:ShowImage[];title?:string}){return images.length>0?<section className="show-section"><h2>{title}</h2><div className="show-gallery">{images.slice(0,8).map(photo=><a key={photo.src} href={photo.src} target="_blank" rel="noopener noreferrer" aria-label={`Apri fotografia: ${photo.alt}`} data-event="show_gallery_open"><ImageAsset image={photo}/></a>)}</div></section>:null}
export function ShowCredits({show}:{show:Show}){return show.credits.length>0?<section className="show-section show-credits" aria-labelledby="show-credits-title"><h2 id="show-credits-title">Crediti</h2><dl>{show.credits.map(credit=><div key={credit.label}><dt>{credit.label}</dt><dd>{credit.names.map(name=><span key={name}>{name}</span>)}</dd></div>)}</dl></section>:null}
export function ShowFAQ({show}:{show:Show}){return show.faq.length>0?<section className="show-section show-faq" aria-labelledby="show-faq-title"><h2 id="show-faq-title">Informazioni pratiche</h2>{show.faq.map(faq=><details key={faq.question}><summary>{faq.question}<span aria-hidden="true">+</span></summary><p>{faq.answer}</p></details>)}</section>:null}
export function RelatedShows({show}:{show:Show}){const related=show.relatedShows.flatMap(slug=>{const item=getShow(slug);return item&&item.slug!==show.slug?[item]:[]}).slice(0,3);return related.length>0?<section className="show-section"><h2>Altri spettacoli</h2><div className="show-related">{related.map(item=><article key={item.slug}><Link href={showPath(item)} data-event="show_related_show_click"><ImageAsset image={item.heroImage}/><h3>{item.title}</h3><p>{item.tagline}</p><Icon name="arrow"/></Link></article>)}</div></section>:null}
export function ShowFinalCTA({show,now}:{show:Show;now:number}){const tickets=mainTicket(show,now);return <section className="show-section show-final"><h2>Ci vediamo a teatro.</h2><div className="show-actions">{tickets&&<TicketLink href={tickets} event="show_ticket_click_final"/>}<Link className="button secondary" href="/teatro/" data-event="show_back_to_theatre">Torna a Teatro<Icon name="arrow"/></Link></div></section>}
function ShowFooter(){return <footer className="social-area"><p>Seguimi anche qui.</p><nav aria-label="Profili social"><ul>{socials.map(social=><li key={social.name}><a href={social.href} target="_blank" rel="noopener noreferrer" data-event={`show_social_${social.icon}`}><Icon name={social.icon} className={`social-icon ${social.icon}`}/><span>{social.name}</span></a></li>)}</ul></nav></footer>}
export function ShowTemplate({show,now}:{show:Show;now:number}){return <div className="show-page"><a className="skip-link" href="#show-content">Vai al contenuto</a><div className="page-wrap"><Header currentPath="/teatro/"/><main id="show-content"><nav className="show-breadcrumb" aria-label="Percorso"><Link href="/">Home</Link><span aria-hidden="true">/</span><Link href="/teatro/" data-event="show_back_to_theatre">Teatro</Link><span aria-hidden="true">/</span><span aria-current="page">{show.title}</span></nav><ShowHero show={show} now={now}/><ShowIntro show={show}/><ShowDates show={show} now={now}/><ShowGallery images={show.gallery}/>{show.trailer&&<ShowTrailer trailer={show.trailer}/>}<ShowGallery images={show.backstage} title="Dietro le quinte"/><ShowCredits show={show}/><ShowFAQ show={show}/>{show.press.length>0&&<section className="show-section"><h2>Dicono dello spettacolo</h2>{show.press.map(press=><figure key={press.url}><blockquote>{press.text}</blockquote><figcaption><a href={press.url} target="_blank" rel="noopener noreferrer">{press.source}</a></figcaption></figure>)}</section>}<RelatedShows show={show}/><ShowFinalCTA show={show} now={now}/></main><ShowFooter/><HomeInteractions/><ShowInteractions/></div></div>}
