import {site,socials} from './site';

export type PressCategory='Portrait'|'Teatro'|'Eventi'|'Scrittura'|'Backstage';
export type PressPhoto={id:string;title:string;alt:string;category:PressCategory;preview:string;srcSet:string;original:string|null;width:number;height:number;orientation:'Verticale'|'Orizzontale';photographer:string|null;usageNotes:string;downloadLabel:string;downloadName:string};
export type PressBio={id:string;title:string;targetCharacters:number;text:string|null;approved:boolean;verified?:boolean;file?:string};
// Publish a biography only after replacing the placeholder and approving its text.
export const pressData={
 seo:{title:'Press e Media Kit | Peppe Ventura',description:'Bio ufficiali, fotografie, materiali stampa e informazioni professionali di Peppe Ventura per media, eventi e collaborazioni.'},
 hero:{title:'Media kit',subtitle:'Bio, immagini e materiali di Peppe Ventura.',text:'Un punto di riferimento per articoli, eventi, comunicazione e collaborazioni.',src:'/images/about/portrait-900.webp',srcSet:'/images/about/portrait-480.webp 480w, /images/about/portrait-900.webp 900w',width:900,height:920,alt:'Peppe Ventura in bianco e nero, con le mani vicine e lo sguardo rivolto verso l’alto'},
 bios:[
  {id:'breve',title:'Bio breve',targetCharacters:300,text:"Peppe Ventura è autore, attore e presentatore napoletano. Racconta persone e relazioni attraverso teatro, scrittura e video. È autore di L’hai scelto tu e, con Samuele Ciambriello, di Caro prof ti scrivo….",approved:false,verified:true,file:'/press/bio/peppe-ventura-bio-breve-bozza.txt'},
  {id:'media',title:'Bio media',targetCharacters:700,text:"Peppe Ventura è autore, attore e presentatore napoletano. La scrittura, il palco e i video sono i linguaggi con cui osserva persone, relazioni e quotidianità. Nel 2018 pubblica con Samuele Ciambriello Caro prof ti scrivo…, per Rogiosi Editore. Nel 2025 esce L’hai scelto tu. In teatro è in scena in Click 2.0 con Emanuel Ceruti e firma Chiamami Papà insieme a Raffaele Nolli. Nel 2025 riceve il Premio San Gennaro World.",approved:false,verified:true,file:'/press/bio/peppe-ventura-bio-media-bozza.txt'},
  {id:'completa',title:'Bio completa',targetCharacters:1500,text:"Peppe Ventura, nome con cui è conosciuto Giuseppe Ventura, è autore, attore e presentatore napoletano. Il suo lavoro attraversa scrittura, teatro e video, con un’attenzione alle persone e alle relazioni.\n\nLa passione per la scrittura nasce durante gli anni del liceo. Nel 2018 pubblica Caro prof ti scrivo… con Samuele Ciambriello, per Rogiosi Editore: un progetto che mette al centro il dialogo con gli adolescenti e i loro pensieri. Nel 2025 pubblica il romanzo L’hai scelto tu, in cui la storia di Francesco affronta la ricerca di un posto nel mondo, le scelte e la fragilità.\n\nIl percorso teatrale comprende Click 2.0, in scena con Emanuel Ceruti e presentato anche al Teatro Cilea di Napoli. È autore, con Raffaele Nolli, di Chiamami Papà, spettacolo di cui è anche interprete. La data al Teatro Acacia del 9 dicembre 2026 è pubblicata sul circuito TicketOne.\n\nNel 2025 riceve il Premio San Gennaro World, consegnato da Gianni Simioli. I suoi canali digitali affiancano il lavoro dal vivo e la scrittura: modi diversi di entrare in relazione con il pubblico, mantenendo al centro le storie delle persone.",approved:false,verified:true,file:'/press/bio/peppe-ventura-bio-completa-bozza.txt'},
 ] satisfies PressBio[],
 categories:['Portrait','Teatro','Eventi','Scrittura','Backstage'] as PressCategory[],
 photos:[
  {id:'portrait',alt:'Peppe Ventura in maglia a righe davanti a un sipario rosso',title:'Peppe Ventura · ritratto',category:'Portrait',preview:'/images/press/portrait-640.webp',srcSet:'/images/press/portrait-320.webp 320w, /images/press/portrait-640.webp 640w',original:'/images/peppe-960.webp',width:960,height:1280,orientation:'Verticale',photographer:null,usageNotes:'Credito fotografico da confermare.',downloadLabel:'Scarica versione web',downloadName:'peppe-ventura-ritratto-web.webp'},
  {id:'autore',alt:'Peppe Ventura con il libro L’hai scelto tu tra le mani',title:'Con L’hai scelto tu',category:'Scrittura',preview:'/images/press/autore-640.webp',srcSet:'/images/press/autore-320.webp 320w, /images/press/autore-640.webp 640w',original:'/images/writing/portrait-960.webp',width:960,height:1440,orientation:'Verticale',photographer:null,usageNotes:'Credito fotografico da confermare.',downloadLabel:'Scarica versione web',downloadName:'peppe-ventura-autore-web.webp'},
  {id:'scena',alt:'Peppe Ventura in bianco e nero con le mani vicine e lo sguardo verso l’alto',title:'Uno sguardo dalla scena',category:'Teatro',preview:'/images/press/scena-640.webp',srcSet:'/images/press/scena-320.webp 320w, /images/press/scena-640.webp 640w',original:'/press/photos/peppe-ventura-scena.jpg',width:1536,height:1492,orientation:'Orizzontale',photographer:null,usageNotes:'Credito fotografico da confermare.',downloadLabel:'Scarica originale',downloadName:'peppe-ventura-scena.jpg'},
  {id:'palco',alt:'Peppe Ventura di profilo sul palco mentre indica verso il pubblico',title:'Sul palco',category:'Teatro',preview:'/images/press/palco-640.webp',srcSet:'/images/press/palco-320.webp 320w, /images/press/palco-640.webp 640w',original:'/press/photos/peppe-ventura-palco.jpg',width:752,height:1536,orientation:'Verticale',photographer:null,usageNotes:'Credito fotografico da confermare.',downloadLabel:'Scarica originale',downloadName:'peppe-ventura-palco.jpg'},
  {id:'pubblico',alt:'Peppe Ventura visto di spalle sul palco davanti al pubblico',title:'Davanti al pubblico',category:'Teatro',preview:'/images/press/pubblico-640.webp',srcSet:'/images/press/pubblico-320.webp 320w, /images/press/pubblico-640.webp 640w',original:'/press/photos/peppe-ventura-pubblico.jpg',width:1024,height:1536,orientation:'Verticale',photographer:null,usageNotes:'Credito fotografico da confermare.',downloadLabel:'Scarica originale',downloadName:'peppe-ventura-pubblico.jpg'},
  {id:'lettura',alt:'Un libro aperto tra le mani di Peppe Ventura',title:'Tra le pagine',category:'Scrittura',preview:'/images/press/lettura-640.webp',srcSet:'/images/press/lettura-320.webp 320w, /images/press/lettura-640.webp 640w',original:'/press/photos/peppe-ventura-lettura.jpg',width:1152,height:1536,orientation:'Verticale',photographer:null,usageNotes:'Credito fotografico da confermare.',downloadLabel:'Scarica originale',downloadName:'peppe-ventura-lettura.jpg'},
 ] satisfies PressPhoto[],
 projects:[
  {category:'Teatro',title:'Chiamami Papà',description:'Lo spettacolo, i materiali e le informazioni per il pubblico.',href:'/teatro/chiamami-papa/',sectionHref:'/teatro/',sectionLabel:'Tutto il teatro',image:'/images/theatre/chiamami-papa-poster-480.webp',alt:'Locandina ufficiale dello spettacolo Chiamami Papà',width:480,height:600},
  {category:'Libri',title:'L’hai scelto tu',description:'Il libro di Peppe Ventura. Scheda e approfondimenti.',href:'/libri/l-hai-scelto-tu/',sectionHref:'/scrivo/',sectionLabel:'Libri e scrittura',image:'/images/writing/cover-300.webp',alt:'Copertina del libro L’hai scelto tu di Peppe Ventura',width:300,height:400},
  {category:'Video',title:'Dentro e fuori dal palco',description:'I canali ufficiali e la selezione dei contenuti video.',href:'/video/',sectionHref:null,sectionLabel:null,image:'/images/videos/hero-480.webp',alt:'Peppe Ventura con un microfono durante un momento dal vivo',width:480,height:556},
 ],
 pressCoverage:[{"publication": "ANSA", "title": "Premio San Gennaro world 2025, omaggio a Claudio Mattone", "date": "2025-09-26", "href": "https://www.ansa.it/amp/campania/notizie/2025/09/26/premio-san-gennaro-world-2025-omaggio-a-claudio-mattone_eca68cd7-1ddf-42af-918b-7cab2189aa5b.html"},{"publication": "Napoli Magazine", "title": "SPETTACOLI - \"Click 2.0\", con Emanuel Ceruti, Paco De Rosa e Peppe Ventura, al Teatro Cilea", "date": "2025-01-21", "href": "https://www.napolimagazine.com/cultura-gossip/articolo/spettacoli-click-2-0-con-emanuel-ceruti-paco-de-rosa-e-peppe-ventura-al-teatro-cilea-21-01-2025"},{publication:'Metropolis',title:'Dal web alla stampa: Peppe Ventura racconta il suo libro «L’hai scelto tu»',date:'2025-08-05',href:'https://www.metropolisweb.it/2025/08/05/dal-web-alla-stampa-peppe-ventura-racconta-suo-libro-lhai-scelto-tu/'}],
 sources:[{title:'COMICON · Scheda autore',href:'https://napoli.comicon.it/ospiti/806/rai.it'},{title:'Rogiosi · Caro prof ti scrivo…',href:'https://rogiosi.it/product/caro-prof-ti-scrivo/'},{title:'Teatro Cilea · Click 2.0',href:'https://teatrocilea.it/spettacoli/click-2-0/'},{title:'TicketOne · Chiamami Papà',href:'https://www.ticketone.it/event/peppe-ventura-chiamami-papa-teatro-acacia-22006897/'}],
 logos:[],awards:[{year:2025,title:'Premio San Gennaro World',description:'Riconoscimento consegnato a Peppe Ventura da Gianni Simioli.',href:'https://www.ansa.it/amp/campania/notizie/2025/09/26/premio-san-gennaro-world-2025-omaggio-a-claudio-mattone_eca68cd7-1ddf-42af-918b-7cab2189aa5b.html'}],downloads:[] as {title:string;href:string}[],
 contacts:{pressEmail:null as string|null,management:null as string|null},
 facts:{name:site.name,profession:site.descriptor,website:site.origin,socials},
};
