import {Header} from '@/components/home/header';
import {HomeInteractions} from '@/components/home/interactions';
import {Icon} from '@/components/home/icons';
import {cards,site,socials} from '@/content/site';
function HomeCard({card,index}:{card:(typeof cards)[number];index:number}){
 return <article className={`home-card card-${index+1}`}><a href={card.href} data-pending="true" data-event={card.event}><div className="card-image"><img src={card.image} alt="" width="300" height="180" loading="lazy" decoding="async"/></div><div className="card-copy"><h2>{card.title}</h2><p>{card.description}</p></div><span className="card-arrow"><Icon name="arrow"/></span></a></article>;
}
function SocialArea(){return <footer className="social-area"><p>Seguimi anche qui.</p><nav aria-label="Profili social"><ul>{socials.map(s=><li key={s.name}><a href={s.href??'#'} data-pending={s.href?undefined:'social'} aria-disabled={s.href?undefined:true} title={s.href?undefined:'Canale ufficiale da collegare'} data-event={s.event} target={s.href?'_blank':undefined} rel={s.href?'noopener noreferrer':undefined}><Icon name={s.icon} className={`social-icon ${s.icon}`}/><span>{s.name}</span></a></li>)}</ul></nav></footer>}
export default function Home(){
 const jsonLd={'@context':'https://schema.org','@graph':[
 {'@type':'Person','@id':`${site.origin}/#person`,name:site.name,url:`${site.origin}/`,image:`${site.origin}${site.hero}`,jobTitle:['Autore','Attore','Presentatore'],description:site.description,sameAs:socials.flatMap(s=>s.href?[s.href]:[])},
 {'@type':'WebSite','@id':`${site.origin}/#website`,url:`${site.origin}/`,name:site.name,inLanguage:'it-IT',publisher:{'@id':`${site.origin}/#person`}},
 {'@type':'WebPage','@id':`${site.origin}/#webpage`,url:`${site.origin}/`,name:'Peppe Ventura | Autore, Attore e Presentatore',isPartOf:{'@id':`${site.origin}/#website`},about:{'@id':`${site.origin}/#person`},inLanguage:'it-IT'}]};
 return <div className="home-shell"><a className="skip-link" href="#contenuto">Vai al contenuto</a><div className="curtain-backdrop" aria-hidden="true"/><div className="stage-floor" aria-hidden="true"/><div className="page-wrap"><Header/><main id="contenuto"><section className="hero" aria-labelledby="hero-title"><picture className="hero-portrait"><source srcSet="/images/peppe-480.webp 480w, /images/peppe-960.webp 960w" sizes="(max-width: 767px) 330px, 520px" type="image/webp"/><img src={site.hero} alt={site.heroAlt} width="1152" height="1536" fetchPriority="high" decoding="async"/></picture><div className="hero-copy"><h1 id="hero-title"><span>PEPPE</span><span>VENTURA</span></h1><p className="sr-only">{site.descriptor}</p><p className="headline">{site.headline}</p><div className="hero-actions"><a className="button primary" href={site.tickets} target="_blank" rel="noopener noreferrer" data-event="ticket_click_home"><Icon name="ticket"/><span>Biglietti</span><Icon name="arrow"/></a><a className="button secondary" href="/chi-sono/" data-pending="true" data-event="about_click_home"><span>Scopri di più</span><Icon name="down"/></a></div></div><div className="home-cards" aria-label="Scopri il mondo di Peppe Ventura">{cards.map((card,index)=><HomeCard card={card} index={index} key={card.href}/>)}</div></section></main><SocialArea/><HomeInteractions/></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,'\\u003c')}}/></div>;
}
