/* Responsive static WebP assets, with intrinsic dimensions and deferred body images. */
/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import {Header} from '@/components/home/header';
import {Icon} from '@/components/home/icons';
import {HomeInteractions} from '@/components/home/interactions';
import {site,socials} from '@/content/site';
import {getBook,bookPath} from '@/content/books';
import {getShow,showPath} from '@/content/shows';
import {relatedArticlesFor} from '@/content/articles';
import {articlePath,readingMinutes,articleText,type Article,type ArticleImage,type InlineText} from '@/lib/article-model';
import {ArticleShare} from './article-share';
import {ArticleTelemetry} from './article-telemetry';
import {ArticleVideo} from './article-video';

function RichText({text}:{text:InlineText[]}){return text.map((run,index)=>{let content:React.ReactNode=run.text;if(run.bold)content=<strong>{content}</strong>;if(run.italic)content=<em>{content}</em>;return run.href?(run.href.startsWith('/')?<Link key={index} href={run.href}>{content}</Link>:<a key={index} href={run.href} target="_blank" rel="noopener noreferrer">{content}<span className="sr-only">, apre una nuova scheda</span></a>):<span key={index}>{content}</span>})}
function EditorialImage({image,hero=false}:{image:ArticleImage;hero?:boolean}){return <figure className={hero?'article-hero-image':'article-body-image'}><img src={image.src} srcSet={image.srcSet} sizes={hero?'(max-width:767px) calc(100vw - 40px), (max-width:1099px) calc(100vw - 48px), 1020px':'(max-width:767px) calc(100vw - 40px), 740px'} width={image.width} height={image.height} alt={image.alt} loading={hero?'eager':'lazy'} fetchPriority={hero?'high':undefined} decoding="async"/>{image.caption&&<figcaption>{image.caption}</figcaption>}</figure>}
function ArticleBody({article}:{article:Article}){return <div className="article-body" id="article-body">{article.content.map((block,index)=>{switch(block.type){
 case 'paragraph':return <p key={index} className={block.lead?'article-lead':undefined}><RichText text={block.text}/></p>;
 case 'heading':return block.level===2?<h2 key={block.id} id={block.id}>{block.text}</h2>:<h3 key={block.id} id={block.id}>{block.text}</h3>;
 case 'quote':return <figure key={index} className="article-quote"><blockquote><p>{block.text}</p></blockquote>{(block.attribution||block.sourceUrl)&&<figcaption>{block.attribution}{block.sourceUrl&&<a href={block.sourceUrl} target="_blank" rel="noopener noreferrer">Fonte<span className="sr-only">, apre una nuova scheda</span></a>}</figcaption>}</figure>;
 case 'image':return <EditorialImage key={index} image={block.image}/>;
 case 'gallery':return <div key={index} className="article-gallery">{block.images.map(image=><EditorialImage key={image.src} image={image}/>)}</div>;
 case 'list':return block.ordered?<ol key={index}>{block.items.map((item,i)=><li key={i}><RichText text={item}/></li>)}</ol>:<ul key={index}>{block.items.map((item,i)=><li key={i}><RichText text={item}/></li>)}</ul>;
 case 'callout':return <aside key={index} className="article-callout" aria-label={block.title}><p className="article-callout-title">{block.title}</p><p><RichText text={block.text}/></p></aside>;
 case 'video':return <ArticleVideo key={index} title={block.title} url={block.url} poster={block.poster}/>;
 }})}</div>}
function ArticleRelated({article,preview}:{article:Article;preview:boolean}){const related=relatedArticlesFor(article);const book=article.relatedBook?getBook(article.relatedBook):undefined;const show=article.relatedShow?getShow(article.relatedShow):undefined;return <>{(related.length>0||preview)&&<section className="article-related" aria-labelledby="article-related-title"><h2 id="article-related-title">Altri appunti</h2><div className="article-related-grid">{preview?[1,2,3].map(number=><article key={number} className="article-related-card article-placeholder"><p className="article-eyebrow">Segnaposto {number}</p><h3>Titolo dell’appunto correlato</h3><p>Qui comparirà un testo originale, scelto per tema o categoria.</p><span className="article-placeholder-status">Contenuto da selezionare</span></article>):related.map(item=><article key={item.slug} className="article-related-card"><Link href={articlePath(item)} data-event="article_related_click">{item.heroImage&&<img src={item.heroImage.src} srcSet={item.heroImage.srcSet} sizes="(max-width:767px) calc(100vw - 40px), 360px" width={item.heroImage.width} height={item.heroImage.height} alt={item.heroImage.alt} loading="lazy" decoding="async"/>}<div><p className="article-eyebrow">{item.category}</p><h3>{item.title}</h3><p>{item.excerpt}</p><span className="article-card-bottom"><time dateTime={item.publishedAt}>{dateLabel(item.publishedAt)}</time><span className="article-arrow"><Icon name="arrow"/></span></span></div></Link></article>)}</div></section>}{book&&<section className="article-linked-work" aria-labelledby="article-book-title"><p className="article-eyebrow">Dallo stesso mondo</p><Link href={bookPath(book)} data-event="article_book_click"><img src={book.cover.src} srcSet={book.cover.srcSet} sizes="100px" width={book.cover.width} height={book.cover.height} alt={book.cover.alt} loading="lazy"/><div><h2 id="article-book-title">{book.title}</h2><span>Scopri il libro</span></div><Icon name="arrow"/></Link></section>}{show&&<section className="article-linked-work"><p className="article-eyebrow">Sul palco</p><Link href={showPath(show)} data-event="article_show_click"><div><h2>{show.title}</h2><span>Scopri lo spettacolo</span></div><Icon name="arrow"/></Link></section>}{article.relatedVideo&&<section className="article-linked-work"><p className="article-eyebrow">Guarda anche</p><a href={article.relatedVideo.href} target="_blank" rel="noopener noreferrer" data-event="article_video_click">{article.relatedVideo.poster&&<img src={article.relatedVideo.poster.src} width={article.relatedVideo.poster.width} height={article.relatedVideo.poster.height} alt={article.relatedVideo.poster.alt} loading="lazy"/>}<div><h2>{article.relatedVideo.title}</h2><span>Guarda il video<span className="sr-only">, in una nuova scheda</span></span></div><Icon name="arrow"/></a></section>}</>}
function dateLabel(date:string){return new Date(date).toLocaleDateString('it-IT',{timeZone:'Europe/Rome',day:'numeric',month:'long',year:'numeric'})}
function ArticleNewsletter(){return <section className="article-newsletter" aria-labelledby="article-newsletter-title"><div><h2 id="article-newsletter-title">Ogni tanto scrivo.</h2><p>La newsletter è in preparazione.</p></div><form aria-describedby="newsletter-status"><label htmlFor="article-newsletter-email">La tua email</label><div><input id="article-newsletter-email" type="email" autoComplete="email" placeholder="Email" disabled/><button type="button" className="button secondary" disabled>Iscriviti</button></div><p id="newsletter-status">Iscrizioni non ancora attive.</p></form></section>}
function ArticleAuthor(){return <section className="article-author" aria-labelledby="article-author-title"><img src="/images/writing/portrait-480.webp" srcSet="/images/writing/portrait-480.webp 480w, /images/writing/portrait-960.webp 960w" sizes="100px" width={480} height={720} alt="Peppe Ventura con il libro L’hai scelto tu tra le mani" loading="lazy" decoding="async"/><div><p className="article-eyebrow">L’autore</p><h2 id="article-author-title">Peppe Ventura</h2><p>{site.descriptor}</p><Link href="/chi-sono/">Chi sono<Icon name="arrow"/></Link></div></section>}
function ArticleFooter(){return <footer className="social-area"><p>Seguimi anche qui.</p><nav aria-label="Profili social"><ul>{socials.map(social=><li key={social.name}><a href={social.href} target="_blank" rel="noopener noreferrer" data-event={`article_social_${social.icon}`}><Icon name={social.icon} className={`social-icon ${social.icon}`}/><span>{social.name}</span></a></li>)}</ul></nav></footer>}
export function ArticleTemplate({article,preview=false}:{article:Article;preview?:boolean}){
 const headings=article.content.filter(block=>block.type==='heading'&&block.level===2);const showToc=article.showToc&&articleText(article).split(/\s+/).length>=1200&&headings.length>2;
 return <div className="article-page"><a className="skip-link" href="#article-content">Vai al contenuto</a><div className="page-wrap"><Header currentPath="/scrivo/"/><main id="article-content"><nav className="article-breadcrumb" aria-label="Percorso"><Link href="/">Home</Link><span aria-hidden="true">/</span><Link href="/scrivo/">Scrivo</Link><span aria-hidden="true">/</span>{preview?<span>Appunti</span>:<Link href="/appunti/">Appunti</Link>}<span aria-hidden="true">/</span><span aria-current="page">{preview?'Anteprima template':article.title}</span></nav>{preview&&<p className="article-preview-notice"><strong>Anteprima del template</strong><span>Testi dimostrativi. Nessun articolo è attribuito a Peppe Ventura.</span></p>}<article><header className="article-hero"><p className="article-eyebrow">{article.category}{preview?' · Anteprima':''}</p><h1>{article.title}</h1>{article.deck&&<p className="article-deck">{article.deck}</p>}<div className="article-meta"><span>{preview?'Firma prevista: ':'di '}<Link href={article.author.url} rel="author">{article.author.name}</Link></span>{article.publishedAt?<time dateTime={article.publishedAt}>{dateLabel(article.publishedAt)}</time>:<span>Data da definire</span>}{article.updatedAt&&<span>Aggiornato il <time dateTime={article.updatedAt}>{dateLabel(article.updatedAt)}</time></span>}<span>{preview?'Tempo di lettura sul testo definitivo':`${readingMinutes(article)} min di lettura`}</span></div></header>{article.heroImage&&<EditorialImage image={article.heroImage} hero/>}<div className="article-reading">{showToc&&<nav className="article-toc" aria-label="Indice dell’appunto"><p>In questo appunto</p><ol>{headings.map(block=>block.type==='heading'?<li key={block.id}><a href={`#${block.id}`}>{block.text}</a></li>:null)}</ol></nav>}<ArticleBody article={article}/><ArticleShare title={preview?article.seo.title:article.title} url={`${site.origin}${articlePath(article)}`} preview={preview}/></div></article><ArticleRelated article={article} preview={preview}/><div className="article-reading"><div className="article-final"><Link className="button primary" href={preview?'/scrivo/':'/appunti/'}>{preview?'Torna a Scrivo':'Torna agli Appunti'}<Icon name="arrow"/></Link></div><ArticleNewsletter/><ArticleAuthor/></div></main><ArticleFooter/><HomeInteractions/>{!preview&&<ArticleTelemetry slug={article.slug}/>}</div></div>
}
