/* Responsive WebP variants are already compressed, with intrinsic dimensions. */
/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import {Header} from '@/components/home/header';
import {Icon} from '@/components/home/icons';
import {HomeInteractions} from '@/components/home/interactions';
import {site,socials} from '@/content/site';
import type {Book,BookImage,EditorialLink} from '@/content/books';

function BookImageAsset({image,hero=false,sizes='(max-width:767px) calc(100vw - 40px), 460px'}:{image:BookImage;hero?:boolean;sizes?:string}){return <img src={image.src} srcSet={image.srcSet} sizes={sizes} width={image.width} height={image.height} alt={image.alt} fetchPriority={hero?'high':undefined} loading={hero?'eager':'lazy'} decoding="async"/>}
export function BookHero({book}:{book:Book}){return <section className="book-hero" aria-labelledby="book-page-title"><div className="book-hero-copy"><p className="book-eyebrow">Libro</p><h1 id="book-page-title">{book.title}</h1>{book.subtitle&&<p className="book-subtitle">{book.subtitle}</p>}<p className="book-byline">di {book.author}</p><p className="book-description">{book.shortDescription}</p></div><figure className="book-cover"><a href={book.cover.src} target="_blank" rel="noopener noreferrer" aria-label={`Apri la copertina di ${book.title}`} data-event="book_gallery_open"><BookImageAsset image={book.cover} hero sizes="(max-width:767px) 240px, 320px"/></a></figure><div className="book-hero-actions book-actions">{book.purchaseLinks.length>0&&<a className="button primary" href="#book-stores" data-event="book_buy_click">Scopri dove trovarlo<Icon name="arrow"/></a>}<a className="button secondary" href="#book-story">Scopri di più<Icon name="down"/></a></div></section>}
export function BookIntro({book}:{book:Book}){return <section className="book-section book-intro" id="book-story" aria-labelledby="book-story-title"><div><p className="book-eyebrow">Il libro</p><h2 id="book-story-title">Di cosa parla</h2>{book.longDescription.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div>{book.introImage&&<figure><a href={book.introImage.src} target="_blank" rel="noopener noreferrer" data-event="book_gallery_open" aria-label={`Apri fotografia: ${book.introImage.alt}`}><BookImageAsset image={book.introImage}/></a></figure>}</section>}
export function BookOrigin({book}:{book:Book}){return book.whyWritten?<section className="book-section book-origin" aria-labelledby="book-origin-title"><div><p className="book-eyebrow">Dietro le pagine</p><h2 id="book-origin-title">{book.whyWritten.title}</h2>{book.whyWritten.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{book.whyWritten.sourceUrl&&<a className="book-source" href={book.whyWritten.sourceUrl} target="_blank" rel="noopener noreferrer">{book.whyWritten.sourceLabel}<Icon name="arrow"/></a>}</div>{book.quotes.length>0&&<div className="book-quotes">{book.quotes.map(quote=><figure key={quote.text}><blockquote><p>“{quote.text}”</p></blockquote><figcaption>{quote.context}<br/><a href={quote.sourceUrl} target="_blank" rel="noopener noreferrer">{quote.sourceLabel}</a></figcaption></figure>)}</div>}</section>:null}
export function BookDetails({book}:{book:Book}){const details=[['Titolo',book.title],['Autore',book.author],['Anno',book.year],['Editore',book.publisher],['ISBN',book.isbn],['Formato',book.format],['Pagine',book.pages],['Lingua',book.language]].filter(([,value])=>value!==undefined&&value!==null);return <section className="book-section book-details" aria-labelledby="book-details-title"><h2 id="book-details-title">Dettagli editoriali</h2><dl>{details.map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="book-small-note">Dati riferiti all’edizione in brossura.</p></section>}
export function BookStores({book}:{book:Book}){return book.purchaseLinks.length>0?<section className="book-section" id="book-stores" aria-labelledby="book-stores-title"><div className="book-section-heading"><h2 id="book-stores-title">Dove trovarlo</h2><p>Il libro, nelle librerie online.</p></div><div className="book-stores">{book.purchaseLinks.map(store=><article className="book-card" key={store.url}><a href={store.url} target="_blank" rel="noopener noreferrer" data-event="book_store_click" aria-label={`Trova ${book.title} su ${store.name}, in una nuova scheda`}><div><h3>{store.name}</h3><p>{store.description}</p><span className="book-small-note">{new URL(store.url).hostname.replace(/^www\./,'')}</span></div><span className="book-arrow"><Icon name="arrow"/></span></a></article>)}</div><p className="book-small-note">Prezzi, disponibilità e condizioni sono indicati dai rivenditori.</p></section>:null}
export function BookGallery({book}:{book:Book}){return book.gallery.length>0?<section className="book-section"><h2>Il libro, fuori dal libro</h2><div className="book-gallery">{book.gallery.slice(0,6).map(image=><a key={image.src} href={image.src} target="_blank" rel="noopener noreferrer" data-event="book_gallery_open" aria-label={`Apri fotografia: ${image.alt}`}><BookImageAsset image={image}/></a>)}</div></section>:null}
function EditorialCard({item,event}:{item:EditorialLink;event:string}){const contents=<>{item.image&&<BookImageAsset image={item.image}/>}<div><h3>{item.title}</h3><p>{item.description}</p>{item.external&&<span className="book-small-note">{new URL(item.href).hostname.replace(/^www\./,'')}</span>}</div><span className="book-arrow"><Icon name="arrow"/></span></>;return <article className="book-card">{item.external?<a href={item.href} target="_blank" rel="noopener noreferrer" data-event={event}>{contents}<span className="sr-only">Apre una nuova scheda.</span></a>:<Link href={item.href} data-event={event}>{contents}</Link>}</article>}
export function BookRelated({book}:{book:Book}){const related=[...book.relatedArticles,...book.relatedVideos].slice(0,4);return related.length>0?<section className="book-section" aria-labelledby="book-related-title"><h2 id="book-related-title">Dallo stesso mondo</h2><div className="book-related">{related.map(item=><EditorialCard key={item.href} item={item} event="book_related_article_click"/>)}</div></section>:null}
export function OtherBooks({book}:{book:Book}){return book.relatedBooks.length>0?<section className="book-section" aria-labelledby="book-others-title"><h2 id="book-others-title">Altri libri</h2><div className="book-related">{book.relatedBooks.slice(0,3).map(item=><EditorialCard key={item.href} item={item} event="book_related_book_click"/>)}</div></section>:null}
export function BookAuthor({book}:{book:Book}){return <section className="book-section book-author" aria-labelledby="book-author-title">{book.authorPortrait&&<BookImageAsset image={book.authorPortrait} sizes="(max-width:767px) 100px, 150px"/>}<div><p className="book-eyebrow">L’autore</p><h2 id="book-author-title">{book.author}</h2><p>{site.descriptor}</p><Link className="book-source" href="/chi-sono/" data-event="book_author_click">Scopri Peppe<Icon name="arrow"/></Link></div></section>}
export function BookFinalCTA({book}:{book:Book}){return <section className="book-section book-final"><h2>Le storie continuano.</h2><div className="book-actions"><Link className="button secondary" href="/scrivo/" data-event="book_back_to_writing">Torna a Scrivo<Icon name="arrow"/></Link>{book.purchaseLinks.length>0&&<a className="button primary" href="#book-stores" data-event="book_buy_click">Dove trovarlo<Icon name="arrow"/></a>}</div></section>}
function BookFooter(){return <footer className="social-area"><p>Seguimi anche qui.</p><nav aria-label="Profili social"><ul>{socials.map(social=><li key={social.name}><a href={social.href} target="_blank" rel="noopener noreferrer" data-event={`book_social_${social.icon}`}><Icon name={social.icon} className={`social-icon ${social.icon}`}/><span>{social.name}</span></a></li>)}</ul></nav></footer>}
export function BookTemplate({book}:{book:Book}){return <div className="book-page"><a className="skip-link" href="#book-content">Vai al contenuto</a><div className="page-wrap"><Header currentPath="/scrivo/"/><main id="book-content"><nav className="book-breadcrumb" aria-label="Percorso"><Link href="/">Home</Link><span aria-hidden="true">/</span><Link href="/scrivo/" data-event="book_back_to_writing">Scrivo</Link><span aria-hidden="true">/</span><span aria-current="page">{book.title}</span></nav><BookHero book={book}/><BookIntro book={book}/><BookOrigin book={book}/><BookDetails book={book}/><BookStores book={book}/>{book.excerpt&&<section className="book-section"><h2>Un estratto</h2><blockquote>{book.excerpt.text}</blockquote></section>}<BookGallery book={book}/>{book.presentations.length>0&&<section className="book-section"><h2>Presentazioni</h2><ol className="book-presentations">{book.presentations.map(event=><li key={event.id}><time dateTime={event.startDate}>{new Date(event.startDate).toLocaleDateString('it-IT',{timeZone:'Europe/Rome',day:'numeric',month:'long',year:'numeric'})}</time><strong>{event.city}</strong><span>{event.venue}</span>{event.url&&<a href={event.url} target="_blank" rel="noopener noreferrer">Scopri<Icon name="arrow"/></a>}</li>)}</ol></section>}{book.press.length>0&&<section className="book-section"><h2>Dicono del libro</h2>{book.press.map(review=><figure key={review.url}><blockquote>{review.text}</blockquote><figcaption><a href={review.url} target="_blank" rel="noopener noreferrer">{review.source}</a></figcaption></figure>)}</section>}<BookRelated book={book}/><OtherBooks book={book}/><BookAuthor book={book}/><BookFinalCTA book={book}/></main><BookFooter/><HomeInteractions/></div></div>}
