import type {Metadata} from 'next';
import Link from 'next/link';
import {Header} from '@/components/home/header';
import {HomeInteractions} from '@/components/home/interactions';
import {Icon} from '@/components/home/icons';
import {PressBioCard} from '@/components/press/press-bio';
import {PressPhotos} from '@/components/press/press-photos';
import {pressData as press} from '@/content/press';
import {site,socials} from '@/content/site';
import './press.css';

const url=`${site.origin}/press/`;
export const metadata:Metadata={title:press.seo.title,description:press.seo.description,alternates:{canonical:'/press/'},robots:{index:site.production,follow:site.production},openGraph:{title:press.seo.title,description:press.seo.description,url,type:'website',locale:'it_IT',siteName:site.name,images:[{url:press.hero.src,width:press.hero.width,height:press.hero.height,alt:press.hero.alt}]},twitter:{card:'summary_large_image',title:press.seo.title,description:press.seo.description,images:[press.hero.src]}};
const schema={'@context':'https://schema.org','@graph':[
 {'@type':'Person','@id':`${site.origin}/#person`,name:site.name,url:`${site.origin}/`,image:`${site.origin}${press.hero.src}`,jobTitle:['Autore','Attore','Presentatore'],description:site.description,sameAs:socials.map(social=>social.href)},
 {'@type':'WebPage','@id':`${url}#page`,url,name:press.seo.title,description:press.seo.description,inLanguage:'it',about:{'@id':`${site.origin}/#person`},isPartOf:{'@id':`${site.origin}/#website`},breadcrumb:{'@id':`${url}#breadcrumb`}},
 {'@type':'BreadcrumbList','@id':`${url}#breadcrumb`,itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:`${site.origin}/`},{'@type':'ListItem',position:2,name:'Press',item:url}]},
]};

export default function PressPage(){return <div className="press-page"><a className="skip-link" href="#press-content">Vai al contenuto</a><div className="page-wrap"><Header currentPath="/press/"/><main id="press-content">
 <nav className="press-breadcrumb" aria-label="Percorso"><Link href="/">Home</Link><span aria-hidden="true">/</span><span aria-current="page">Press</span></nav>
 <section className="press-hero" aria-labelledby="press-title"><div className="press-hero-copy"><p className="press-eyebrow">Press</p><h1 id="press-title"><span className="sr-only">Press e Media Kit di Peppe Ventura</span><span aria-hidden="true">{press.hero.title}</span></h1><p className="press-subtitle">{press.hero.subtitle}</p><p className="press-intro">{press.hero.text}</p><Link className="press-text-link" href="/chi-sono/">La persona e il percorso<Icon name="arrow"/></Link></div><picture className="press-portrait"><source type="image/webp" srcSet={press.hero.srcSet} sizes="(max-width:767px) calc(100vw - 40px), 600px"/><img src={press.hero.src} alt={press.hero.alt} width={press.hero.width} height={press.hero.height} fetchPriority="high" decoding="async"/></picture></section>
 <nav className="press-jump-links" aria-label="Materiali stampa"><a href="#bio">Bio</a><a href="#foto">Foto</a><a href="#progetti">Progetti</a><a href="#rassegna">Rassegna stampa</a><a href="#contatti-stampa">Contatti</a></nav>
 <section className="press-section" id="bio" aria-labelledby="bio-title"><div className="press-section-heading"><div><p className="press-eyebrow">Le parole</p><h2 id="bio-title">Bio ufficiali</h2></div><p>Testi da fonti verificate, in attesa di approvazione.</p></div><div className="press-bio-grid">{press.bios.map(bio=><PressBioCard key={bio.id} bio={bio}/>)}</div><details className="press-sources"><summary>Fonti delle bio</summary><p>Ricerca aggiornata al 1 ottobre 2026. Per Caro prof ti scrivo… si usa il 2018 indicato dall’editore, che corregge il 2019 riportato nella scheda COMICON.</p><ul>{press.sources.map(source=><li key={source.href}><a href={source.href} target="_blank" rel="noopener noreferrer">{source.title}<span className="sr-only">, apre una nuova scheda</span></a></li>)}</ul><p>Le fonti giornalistiche sono disponibili anche nella rassegna stampa.</p></details></section>
 <section className="press-section" id="foto" aria-labelledby="foto-title"><div className="press-section-heading"><div><p className="press-eyebrow">Le immagini</p><h2 id="foto-title">Foto ufficiali</h2></div><p>Originali e versioni web, indicati per ogni immagine.</p></div><PressPhotos photos={press.photos} categories={press.categories}/></section>
 <section className="press-section press-facts" aria-labelledby="facts-title"><div><p className="press-eyebrow">In breve</p><h2 id="facts-title">Peppe Ventura</h2><Link className="press-text-link" href="/chi-sono/">Chi sono<Icon name="arrow"/></Link></div><dl><div><dt>Nome</dt><dd>{press.facts.name}</dd></div><div><dt>Professione</dt><dd>{press.facts.profession}</dd></div><div><dt>Sito</dt><dd><Link href="/">Sito ufficiale di Peppe Ventura</Link></dd></div><div><dt>Social</dt><dd className="press-fact-socials">{socials.map(social=><a key={social.name} href={social.href} target="_blank" rel="noopener noreferrer">{social.name}<span className="sr-only">, apre una nuova scheda</span></a>)}</dd></div></dl></section>
 <section className="press-section" id="progetti" aria-labelledby="projects-title"><div className="press-section-heading"><div><p className="press-eyebrow">Palco, parole, immagini</p><h2 id="projects-title">Progetti in evidenza</h2></div></div><div className="press-project-grid">{press.projects.map(project=><article key={project.href} className="press-project press-card"><Link href={project.href} data-event="press_project_click" className="press-project-main"><div className="press-project-image"><img src={project.image} alt={project.alt} width={project.width} height={project.height} loading="lazy" decoding="async"/></div><div className="press-project-copy"><p className="press-eyebrow">{project.category}</p><h3>{project.title}</h3><p>{project.description}</p><span className="press-text-link">Scopri di più<Icon name="arrow"/></span></div></Link>{project.sectionHref&&<Link className="press-project-section" href={project.sectionHref}>{project.sectionLabel}<Icon name="arrow"/></Link>}</article>)}</div></section>
 <section className="press-section" id="rassegna" aria-labelledby="coverage-title"><div className="press-section-heading"><div><p className="press-eyebrow">Articoli e incontri</p><h2 id="coverage-title">Rassegna stampa</h2></div></div><ul className="press-coverage">{press.pressCoverage.map(item=><li key={item.href}><a href={item.href} target="_blank" rel="noopener noreferrer" data-event="press_article_click"><div><p className="press-eyebrow">{item.publication}</p><h3>{item.title}</h3><time dateTime={item.date}>{new Date(item.date).toLocaleDateString('it-IT',{timeZone:'UTC',day:'numeric',month:'long',year:'numeric'})}</time></div><span className="press-arrow"><Icon name="arrow"/></span><span className="sr-only">Apre l’articolo in una nuova scheda</span></a></li>)}</ul></section>
 {press.awards.length>0&&<section className="press-section" aria-labelledby="press-awards-title"><div className="press-section-heading"><div><p className="press-eyebrow">Riconoscimenti</p><h2 id="press-awards-title">Premio San Gennaro World</h2></div></div>{press.awards.map(award=><article className="press-kit" key={award.title}><div><p className="press-eyebrow">{award.year}</p><h3>{award.title}</h3><p>{award.description}</p></div><a className="press-text-link" href={award.href} target="_blank" rel="noopener noreferrer">Leggi su ANSA<Icon name="arrow"/><span className="sr-only">, apre una nuova scheda</span></a></article>)}</section>}
 <section className="press-section press-kit" aria-labelledby="kit-title"><div><p className="press-eyebrow">Tutto in un documento</p><h2 id="kit-title">Il press kit</h2><p>Il PDF con bio, fotografie e materiali stampa è in preparazione.</p></div>{press.downloads.length?press.downloads.map(file=><a key={file.href} className="button primary" download href={file.href} data-event="press_kit_download">{file.title}<Icon name="down"/></a>):<span className="press-status">PDF non ancora disponibile</span>}</section>
 <section className="press-section press-contacts" id="contatti-stampa" aria-labelledby="contacts-title"><div><p className="press-eyebrow">Parliamone</p><h2 id="contacts-title">Contatti stampa</h2><p>Per interviste, materiali e richieste professionali.</p>{press.contacts.pressEmail?<a className="press-text-link" href={`mailto:${press.contacts.pressEmail}`} data-event="press_contact_click">{press.contacts.pressEmail}</a>:<p className="press-contact-status">Email stampa e riferimento management da confermare.</p>}</div><div className="press-contact-actions"><Link className="button primary" href="/contatti/" data-event="press_contact_click">Per altre richieste<Icon name="arrow"/></Link><Link className="press-text-link" href="/chi-sono/">Conosci Peppe<Icon name="arrow"/></Link></div></section>
 </main><footer className="social-area"><p>Seguimi anche qui.</p><nav aria-label="Profili social"><ul>{socials.map(social=><li key={social.name}><a href={social.href} target="_blank" rel="noopener noreferrer" data-event={`press_social_${social.icon}`}><Icon name={social.icon} className={`social-icon ${social.icon}`}/><span>{social.name}</span></a></li>)}</ul></nav></footer><HomeInteractions/></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/></div>}
